# Generated by Django 3.0.5 on 2020-05-13 16:16

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('org_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=100)),
                ('org_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('org_city', models.CharField(blank=True, max_length=45, null=True)),
                ('org_state', models.CharField(blank=True, max_length=45, null=True)),
                ('org_country', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'org',
            },
        ),
        migrations.CreateModel(
            name='OrgSubdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_dom', models.CharField(max_length=45)),
                ('org_subdom', models.CharField(max_length=45)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('org_code', models.ForeignKey(db_column='org_code', on_delete=django.db.models.deletion.CASCADE, related_name='orgsubdoms', to='PkApp.Org')),
            ],
            options={
                'db_table': 'org_subdom',
                'unique_together': {('org_code', 'org_dom', 'org_subdom')},
            },
        ),
        migrations.CreateModel(
            name='Seq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.IntegerField()),
                ('seq_type', models.CharField(max_length=15)),
                ('seq_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('org_code', models.ForeignKey(db_column='org_code', on_delete=django.db.models.deletion.CASCADE, related_name='seqs', to='PkApp.Org')),
            ],
            options={
                'db_table': 'seq',
                'unique_together': {('org_code', 'seq_num', 'seq_type')},
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(max_length=45)),
                ('org_dom', models.CharField(max_length=45)),
                ('org_subdom', models.CharField(max_length=45)),
                ('org_seq', models.IntegerField()),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_type', models.CharField(blank=True, max_length=15, null=True)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('answer_hel_field', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.CharField(max_length=45)),
                ('created_datetime', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('auth', compositefk.fields.CompositeForeignKey(db_column='org_seq', null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, related_name='auths', to='PkApp.OrgSubdom', to_fields={'org_code': compositefk.fields.LocalFieldValue('org_code'), 'org_dom': compositefk.fields.LocalFieldValue('org_dom'), 'org_subdom': compositefk.fields.LocalFieldValue('org_subdom')})),
            ],
            options={
                'db_table': 'auth',
                'unique_together': {('org_code', 'org_dom', 'org_subdom', 'org_seq')},
            },
        ),
    ]
